import "../styles/index.scss";
// import "../lessons/lesson2";
// import "../lessons/lesson3";
// import "../lessons/lesson4";
// import "../lessons/lesson5";
// import "../lessons/lesson6";
// import "../lessons/lesson7";
// import "../lessons/lesson8";
// import "../lessons/lesson9";
// import "../lessons/lesson10";
import "../lessons/lesson11";
// import "../lessons/lesson12";
